// app/layout.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="p-4 bg-blue-600 text-white">
          <h1>My App Header</h1>
        </header>
        <main className="p-6">{children}</main>
        <footer className="p-4 bg-gray-800 text-white">Footer</footer>
      </body>
    </html>
  );
}
