// app/layout.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Store Ease",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
